config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  root 'companies#index'

  resources :companies, only: [:index, :show, :create, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ActiveRecord::Base
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/companies_controller.rb
class CompaniesController < ActionController::Base

  def create
    domain = params.dig('company', 'domain').to_s
    return redirect_to :companies, alert: 'No domain' if domain.blank?

    @company = Company.find_by(domain: domain)
    return redirect_to :companies, alert: 'Domain in system' if @company.present?

    company = Clearbit.find_by_domain(domain)
    return redirect_to :companies, notice: 'Company was not saved' if company.blank?

    @company = Company.find_or_create_by(clearbit_id: company['id'])

    @company.update(company.slice('logo', 'name', 'company_type', 'domain',
                                  'description', 'industry', 'money_raised',
                                  'market_cap', 'annual_revenue',
                                  'location', 'number_of_employees'))
    redirect_to :companies, notice: 'New company saved'
  end

  def index
    @company = Company.new
    @companies = Company.select(:id, :logo, :name, :company_type).order('likes DESC').all
  end

  def show
    @company = Company.find_by(id: params[:id])
    return redirect_to :companies, alert: 'No company found' if @company.blank?
  end

  def update
    @company = Company.find_by(id: params[:id])
    return redirect_to :companies, alert: 'No company found' if @company.blank?

    @company.update(likes: @company.likes.to_i + 1)
    redirect_to company_path(@company), notice: 'Liked'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/companies/index.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: name %>
<% end %>

<%= form_with model: @company do |form| %>
  <%= form.text_field :domain %>
  <%= form.submit %>
<% end %>

<table border="1">
  <tr>
    <td>Logo</td>
    <td>Name</td>
    <td>Type</td>
    <td>Show</td>
  </tr>
  <% @companies.each do |c| %>
  <tr>
    <td><%if c.logo %>
          <%= image_tag c.logo %>
        <% end %>
    </td>
    <td><%= c.name %></td>
    <td><%= c.company_type %></td>
    <td><%= link_to 'Show', c %></td>
  </tr>
  <% end %>
</table>

app/views/companies/show.html.erb
<%= link_to 'Back', companies_path %>


<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: name %>
<% end %>

<div>Name:</div>
<div><%= @company.name %></div>
<div>Type:</div>
<div><%= @company.company_type %></div>
<div>Domain:</div>
<div><%= @company.domain %></div>
<div>Description:</div>
<div><%= @company.description%></div>
<div>Industry:</div>
<div><%= @company.industry %></div>
<div>Money Raised</div>
<div><%= @company.money_raised %></div>
<div>Market Cap: </div>
<div><%= @company.market_cap %></div>
<div>Annual Revenue: </div>
<div><%= @company.annual_revenue %></div>
<div>Location</div>
<div><%= @company.location %></div>
<div>Number of employees: </div>
<div><%= @company.number_of_employees %></div>
<div>Likes: </div>
<div><%= @company.likes %></div>

<%= form_with model: @company do |form| %>
  <%= form.hidden_field :like %>
  <%= form.submit 'Like' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Equitybee</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>